server:
  port: 8085

spring:
  application:
    name: person
eureka:
  client:
    fetch-registry: true # 获取注册信息, 默认为true
    registry-fetch-interval-seconds: 10 # 多长时间去Eureka服务端抓取服务列表信息
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka,http://127.0.0.1:8762/eureka
