server:
  port: 8761
eureka:
  server:
    eviction-interval-timer-in-ms: 10000 # 10秒清理一次不可用的服务表
    enable-self-preservation: false # 关闭保护机制
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/
spring:
  profiles: eureka1
  application:
    name: eureka-server

---

server:
  port: 8762
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
  server:
    eviction-interval-timer-in-ms: 10000 # 10秒清理一次不可用的服务表
    enable-self-preservation: false
spring:
  profiles: eureka2
  application:
    name: eureka-server